title: Alexander Isiani
description: Portfolio Website

remote_theme: "mmistakes/minimal-mistakes"

baseurl: "/alexanderisiani.github.io"
url: "https://thealisiani94.github.io"

plugins:
  - jekyll-include-cache

navigation:
  - title: "Overview"
    url: "/"
  - title: "Research"
    url: "/research/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Engagements"
    url: "/engagements/"
  - title: "Honors"
    url: "/honors/"
  - title: "Creative"
    url: "/creative/"
  - title: "CV"
    url: "/cv/"
